load("phri_log.mat")
dt = 0.002
time = 0:dt:((length(f) - 1)*dt);

figure(1)
plot(time, f)
title("Force")
xlabel("Time [s]")
ylabel("Force [N]")
legend("x", "y", "z", "rx", "ry", "rz")

figure(2)
plot(time, qs)
title("Joints")
xlabel("Time [s]")
ylabel("Joint rot [rad] / Pos [m]")
legend("Base pos x", "Base pos y", "Base rot x", "Base rot y", "Joint 1", "Joint 2", "Joint 3", "Joint 4", "Joint 5", "Joint 6")

figure(3)
plot(time, v_cmd)
title("Velocity commands")
xlabel("Time [s]")
ylabel("Command")
legend("Base forward", "", "Base rotation", "Joint 1", "Joint 2", "Joint 3", "Joint 4", "Joint 5", "Joint 6")

time = 0:dt:((length(x1s) - 1)*dt);

figure(4)
plot(time, x1s)
title("x1: Position")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(5)
plot(time, x2s)
title("x2: Speed")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(6)
plot(time, x2dots)
title("x2 dots: Acceleration")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(7)
plot(time, p_refs)
title("Position reference")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(8)
plot(time, p_dot_refs)
title("Position reference dot")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(9)
plot(time, vel_refs)
title("Velocity reference (Task space)")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(10)
plot(time, ee_positions)
title("Global End effector positions (Task space)")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(11)
plot(time, ee_positions_desired)
title("Desired end effector position (Task space)")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")

figure(12)
plot(time, force_terms)
title("Simulated force (Force term)")
xlabel("Time [s]")
ylabel("Value")
legend("x", "y", "z", "rx", "ry", "rz")
